---
title: "p8105_hw2_bs3142"
author: "Bingyu Sun"
date: "9/30/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## Problem 1
```{r}
my_nyc_transit_data = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>%
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>%
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))
```

## Problem 2

Question 1
```{r}
my_wheel_data =
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 1, range = ("A2:N258")) %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(sports_balls = as.integer(sports_balls))
```

Question 2
```{r}
my_precip_2017_data = 
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 3, skip = 1) %>%
  janitor::clean_names() %>%
  rename(precipitation_in = total) %>%
  mutate(year = "2017") %>%
  filter(!is.na(month), !is.na(precipitation_in))
```

```{r}
my_precip_2016_data =
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 4, skip = 1) %>%
  janitor::clean_names() %>%
  rename(precipitation_in = total) %>%
  mutate(year = "2016") %>%
  filter(!is.na(month), !is.na(precipitation_in))
```

```{r}
my_combined_precip_data =
  bind_rows(my_precip_2016_data, my_precip_2017_data) %>%
  mutate(month = month.name[month])
```

## Problem 3

```{r}
library(p8105.datasets)
data(brfss_smart2010)
```

```{r}
my_brfss_data = 
  brfss_smart2010 %>%
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>%
  select(-(class:question), -sample_size, -(confidence_limit_low:geo_location)) %>%
  spread(key = response, value = data_value) %>%
  janitor::clean_names() %>%
  mutate(prop_excellent_and_very_good = (excellent + very_good))
```

