p8105\_hw2\_bs3142
================
Bingyu Sun
9/30/2018

``` r
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse) # load tidyverse library
```

    ## ── Attaching packages ─────────────────────────────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
    ## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
    ## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
    ## ✔ readr   1.1.1     ✔ forcats 0.3.0

    ## ── Conflicts ────────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)    # load readxl library

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)       # set graph format

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

### Problem 1 NYC Transit Data

#### Section 1: Data Manipulation

**Data cleaning**

-   Retain line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance
-   Convert the entry variable from character to a logical variable

``` r
my_nyc_transit_data = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  # import nyc transit data
  janitor::clean_names() %>% # clean variable names
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>% 
  # specify variables
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE)) # Convert entry variable to logical variable
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

**Summary**

1.  Variables in the dataset

    -   The dataset contains information about NYC transit, like station location, routes served in each station, station entrance type, vending, and ADA compliance.

2.  Data cleaning steps

    -   I created a data frame for cleaning raw NYC Transit data. The dataset is imported using a relative path and names are cleaned by janitor function. Specific variables in the dateset are selected. Furthermore, the entry variable has been converted to a logical vector. The resulting dataset consists of **1868** rows by **19** columns.

3.  Data assessment

    -   The data is untidy. There are 11 columns of route numbers that should be organized into a single column under route number with a corresponding column for route names.

#### Section 2: Data features

**1. How many distinct stations are there?**

``` r
distinct_my_nyc_transit_data = 
  my_nyc_transit_data %>%
  distinct(line, station_name, .keep_all = TRUE) 
# make stations distinct

nrow(distinct_my_nyc_transit_data) # count number of rows
```

    ## [1] 465

There are **465** distinct train stations.

**2. How many stations are ADA compliant?**

``` r
distinct_my_nyc_transit_data %>%
  filter(ada == "TRUE") %>% # get ADA compliant stations
  count 
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    84

**84** of the 465 stations are ADA compliant.

**3. What proportion of station entrances / exits without vending allow entrance?**

``` r
nrow(filter(my_nyc_transit_data, vending == "NO", entry == "TRUE")) / nrow(filter(my_nyc_transit_data, vending == "NO")) # calc proportion
```

    ## [1] 0.3770492

**37.7%** of station without vending allow entrance.

#### Section 3: Reformat data

-   Transform route number and route name to distinct variables

``` r
tidy_my_nyc_transit_data =
  my_nyc_transit_data %>%
  gather(key = "route_number", value = "route_name", route1:route11) %>% 
  # reformat route1 to route11 into two columns
  distinct(line, station_name, .keep_all = TRUE) %>%
  filter(route_name == "A") %>% # get stations that serve train A
  filter(ada == "TRUE") # ADA compliant stations that serve train A
```

**How many distinct stations serve the A train? Of the stations that serve the A train, how many are ADA compliant?**

-   There are **60** distinct stations serve Train A, and **17** of them are ADA compliant.

### Problem 2 Mr. Trash Wheel

#### Section 1: Data Manipulation of Mr. Trash Wheel sheet

**Data Cleaning**

-   specify the sheet in the Excel file and to omit columns containing notes (using the range argument and cell\_cols() function)
-   use reasonable variable names
-   omit rows that do not include dumpster-specific data
-   rounds the number of sports balls to the nearest integer and converts the result to an integer variable (using as.integer)

``` r
my_wheel_data =
  read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 1, range = cell_cols("Dumpster:Homes Powered")) %>% # import wheel data
  janitor::clean_names() %>% # clean names
  select(-x_1) %>% # remove notes
  filter(!is.na(dumpster)) %>% # remove rows without dumpster info
  mutate(sports_balls = as.integer(sports_balls)) # round values of sports balls to integers
```

    ## Warning in letter_to_num(x): NAs introduced by coercion to integer range

#### Section 2: Data Manipulation of prcp 2016 & 2017

**Data Cleaning**

-   Omit rows without precipitation data and add a variable year.
-   Combine datasets and convert month to a character variable (the variable month.name is built into R and should be useful).

Prcp\_2017:

``` r
my_prcp_2017_data = 
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 4, skip = 1) %>% # import 2017 precipitation data
  janitor::clean_names() %>% # clean names
  rename(precipitation_in = total) %>% # rename a column
  mutate(year = "2017") %>% # add a column showing year
  filter(!is.na(month), !is.na(precipitation_in)) # filter out NA
```

Prcp\_2016:

``` r
my_prcp_2016_data =
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 5, skip = 1) %>% # import 2016 precipitation data
  janitor::clean_names() %>% # clean names
  rename(precipitation_in = total) %>% # rename a column
  mutate(year = "2016") %>% # add a column showing year
  filter(!is.na(month), !is.na(precipitation_in)) # filter out NA
```

Prcp 2016 & 2017:

``` r
my_combined_prcp_data =
  bind_rows(my_prcp_2016_data, my_prcp_2017_data) %>% 
  # combine 2016 and 2017 data
  mutate(month = month.name[month])
  # change month to month name
```

**Summary**

**1. Mr. Trash Wheel**

The dataset consists of **285** rows by **14** columns. There are **285** dumpsters recorded from year 2014 to 2018. Information like date, trash amount, and types are included. The median number of sports balls in a dumpster in 2016 was **26**.

**2. Precipitation 2017**

The dataset consists of 12 observations of monthly amount of precipitation in 2017. The total precipitation in 2017 was **32.93** inches.

**3. Precipitation 2016**

The dataset consists of 12 observations of monthly amount of precipitation in 2016. The total precipitation in 2016 was **39.95** inches.

**4. Precipitation 2016 & 2017**

The dataset is a combined dataset for 2016 and 2017 precipitation data. It consists of **24** observations, one per month. One difference in the dataset is that the numeric monthes are converted to character variables.

### Problem 3

#### Section 1: Data Import

``` r
library(p8105.datasets)
data(brfss_smart2010) # import BRFSS data
```

#### Section 2: Data Manipulation

-   Format the data to use appropriate variable names
-   Focus on the “Overall Health” topic
-   Exclude variables for class, topic, question, sample size, and everything from lower confidence limit to GeoLocation
-   Structure data so that values for Response (“Excellent” to “Poor”) are column names / variables which indicate the proportion of subjects with each response (which are values of Data\_value in the original dataset)
-   Create a new variable showing the proportion of responses that were “Excellent” or “Very Good”

``` r
my_brfss_data = 
  brfss_smart2010 %>%
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>% 
  # select rows based on overall health
  select(-(class:question), -sample_size, -(confidence_limit_low:geo_location)) %>%
  spread(key = response, value = data_value) %>% 
  # reformat response
  janitor::clean_names() %>%
  mutate(prop_excellent_and_very_good = (excellent + very_good)) # add a column of proportion for excellent and very good
```

**Summary**

**1. How many unique locations are included in the dataset? Is every state represented? What state is observed the most?**

The dataset contains **404** unique locations, in **51** states. Therefore, every state is represented. **NJ** (New Jersey) state is observed the most.

**2. In 2002, what is the median of the “Excellent” response value?**

In 2002, the median of the "Excellent" response value is **23.6**.

#### Section 3: Plots

1.  **Histogram** of “Excellent” response values in the year 2002

``` r
my_brfss_data %>%
  select(year, excellent) %>%
  filter(year == "2002") %>%
  # retain only 2002 data
  ggplot(aes(x = excellent)) +
  geom_histogram() +
  labs(x = "Excellent",
       title = "Histogram of Excellent response values in 2002") # plot histogram
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

    ## Warning: Removed 2 rows containing non-finite values (stat_bin).

<img src="p8105_hw2_bs3142_files/figure-markdown_github/Histogram of Excellent in 2002-1.png" width="90%" />

1.  **Scatterplot** showing the proportion of “Excellent” response values in New York County and Queens County (both in NY State) in each year from 2002 to 2010

``` r
my_brfss_data %>%
  select(year, locationdesc, excellent) %>%
  filter(locationdesc %in% c("NY - New York County", "NY - Queens County")) %>%
  # retain New York County and Queens County info
  ggplot(aes(x = year, y = excellent, color = locationdesc)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  labs(title = "Scatterplot of Excellent response proportion in New York County and Queens Country in 2002 to 2010") # plot scatterplot
```

    ## `geom_smooth()` using method = 'loess' and formula 'y ~ x'

<img src="p8105_hw2_bs3142_files/figure-markdown_github/Scatterplot of excellent response proportion in NY country and Queens County from 2002-2010-1.png" width="90%" />
